version: "3.7"
services:
    react-admin-db:
        container_name: react-admin-db
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ".:/app"
            - "/app/node_modules"
        ports:
            - "3000:3000"
